### PR TITLE
Bump ember-cli-babel

### PR DESCRIPTION
**Pull request by krasnoukhov**
Fixes deprecation warnings.

### CODE REVIEW

**Comment by rmachielse** [comment]
@bmac could you merge this?

**Comment by rmachielse** [comment]
@bmac thanks! Do you intend to cut a release too?

**Comment by bmac** [comment]
Sure, currently re-installing node on my laptop but I'll ping you when the release is pushed.

**Comment by rmachielse** [comment]
Thanks, appreciate it!

**Comment by bmac** [comment]
Just published 1.2.0 https://www.npmjs.com/package/ember-cli-content-for-config

**Comment by rmachielse** [comment]
Thank you so much 🙏💪

**Pull request merged**
