### PR TITLE
Upgrade ember-cli-babel

### LINKED ISSUE #2: Resolve `ember-cli-babel` deprecation
This addon seems outdated, is there any chance a pr to upgrade it's dependencies gets merged?
Or am I missing out on a new solution for this?

### PR DESCRIPTION
**Pull request by rmachielse**
Fixes #2

### CODE REVIEW

**Comment by rmachielse** [comment]
@bmac I only upgraded `ember-cli-babel` now.

I guess the whole addon needs to be updated to a recent ember-cli version too but this should be enough for this issue.

**Comment by bmac** [comment]
Thanks @rmachielse.

**Comment by bmac** [comment]
Published as `ember-cli-content-for-config@1.1.0`

**Comment by rmachielse** [comment]
@bmac thank you very much!

**Pull request merged**
